
class_dict = {
     "ENG": {"ENG 105":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring"],
                       "WhenTakeYear" : 1,
                       "WhenTakeSemester": 1,
                       "Summary":"An introduction to research, writing, and rhetorical practices employed in academic and professional contexts. The course examines the operation of genres, the audiences they address, and the purposes they serve. The course focuses on the analysis and development of student writing and rhetorical practice. Assignments include research essays, digital compositions, and oral presentations. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans' Office.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []}

        },

    "MTH" : {"MTH 141":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring", "Summer", "Winter"],
                       "WhenTakeYear" : 1,
                       "WhenTakeSemester": 1,
                       "Summary":"Beginning of a three-semester sequence in calculus for students of mathematics, natural sciences, and engineering. Covers differentiation and integration with applications.  This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office. This course is the same as MTH 136 + 137 and course repeat rules will apply. Students should consult with their major department regarding any restrictions on their degree requirements.",
                       "Pre-Requisite": ["MTH 108", "MTH 114", "MTH 115", "MTH 121", "MTH 131", "ULC 148","MTH 109", "MTH 113"],
                       "Co-Requisite": []},
            "MTH 142":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring", "Summer", "Winter"],
                       "WhenTakeYear" : 1,
                       "WhenTakeSemester": 2,
                       "Summary":"Differentiation and integration of transcendental functions; infinite sequences; series and power series; integration methods; additional topics in analytic geometry.  This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office. This course is the same as MTH 138 and MTH 139 and course repeat rules will apply. Students should consult with their major department regarding any restrictions on their degree requirements.",
                       "Pre-Requisite": ["MTH 141",  "MTH 136" , "MTH 137"],
                       "Co-Requisite": []},
            "MTH 309":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring", "Summer"],
                       "WhenTakeYear" : 3,
                       "WhenTakeSemester": 1,
                       "Summary":"Differentiation and integration of transcendental functions; infinite sequences; series and power series; integration methods; additional topics in analytic geometry.  This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office. This course is the same as MTH 138 and MTH 139 and course repeat rules will apply. Students should consult with their major department regarding any restrictions on their degree requirements.",
                       "Pre-Requisite": ["MTH 142",  "MTH 154" , "MTH 138", "MTH 139"],
                       "Co-Requisite": []},

            },


    "CSE" : {"CSE 115":{"Proffesor":{"Carl Alphonce" :{"Rating": 3.4,
                                                     "Semester": "Spring"},
                                   "Paul Dickson" :{"Rating": 4.4,
                                                    "Semester" : "Spring"},
                                    "Eric Mikida" :{"Rating": 4.3,
                                                    "Semester": "Spring"}, 
                                    "Mathew Hertz" :{"Rating": 3.7,
                                                     "Semester" : "Fall"}},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring"],
                       "WhenTakeYear" : 1,
                       "WhenTakeSemester": 1,
                       "Summary":"Provides the fundamentals of computer science with an emphasis on applying programming skills to solve problems and increase human efficiency. Topics include variables, data types, expressions, control flow, functions, input/output, data storage, networking, security, selection, sorting, iteration and the use of aggregate data structures such as lists and more general collections. No previous programming experience required.",
                       "Pre-Requisite": ["MTH 115", "ULC 148"],
                       "Co-Requisite": ["MTH 121", "MTH 131", "MTH 141"]},
            
            "CSE 199": {"Proffesor":{"Kenneth Joseph" :{"Rating": 4.4,
                                                     "Semester": "Spring"},
                                   "Karthik Dantu" :{"Rating": 2.3,
                                                    "Semester" : "Spring"},
                                    "Kenneth Regan" :{"Rating": "DNE",
                                                    "Semester": "Spring"}, 
                                    "David Doermann" :{"Rating": 2.3,
                                                     "Semester" : "Fall"},
                                    "Nasrin Akhter" :{"Rating": 3.1,
                                                     "Semester" : "Fall"},
                                    "Atri Rudra" :{"Rating": 3.9,
                                                     "Semester" : "Fall"}},
                        "Credits": 3,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall"],
                       "WhenTakeYear" : 1,
                       "WhenTakeSemester": 1,
                       "Summary":"The three credit UB Seminar is focused on a big idea or challenging issue to engage students with questions of significance in a field of study and, ultimately, to connect their studies with issues of consequence in the wider world. Essential to the UB Curriculum, the Seminar helps students with common learning outcomes focused on fundamental expectations for critical thinking, ethical reasoning, and oral communication, and learning at a university, all within topic focused subject matter. The Seminars provide students with an early connection to UB faculty and the undergraduate experience at a comprehensive, research university. This course is equivalent to any 199 offered in any subject. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade of F or R may not be able to repeat the course during the fall or spring semester.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []},
            "CSE 116":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring","Summer"],
                       "WhenTakeYear" : 1,
                       "WhenTakeSemester": 2,
                       "Summary":"Students will continue to develop the skills introduced in CSE 115 while exploring the details of program execution and the structure of large programs. Emphasizes design decisions that affect the efficiency, expandability, and maintainability of code while analyzing the differences amongst a variety of approaches. Design decisions analyzed include choice of data structures and object-oriented techniques such as encapsulation, polymorphism, and inheritance. Additional topics include the use of recursion, multithreading, parallelism, hardware, graph and tree traversals, asymptotic analysis, divide and conquer, databases, testing, and multi-language integration.",
                       "Pre-Requisite": ["CSE 115", "EAS 230", "EAS 240",  "EAS 999TRCP"],
                       "Co-Requisite": []},
                       
            "CSE 191":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring","Summer"],
                       "WhenTakeYear" : 1,
                       "WhenTakeSemester": 2,
                       "Summary":"Foundational material for further studies in computer science. Topics include logic, proofs, sets, functions, relations, recursion, recurrence relations, mathematical induction, graphs, trees, basic counting theory, regular languages, and context free grammars. This course is the same as MTH 191 and course repeat rules will apply. Students should consult with their major department regarding any restrictions on their degree requirements.",
                       "Pre-Requisite": ["CSE 115", "EAS 230", "EAS 240",  "EAS 999TRCP"],
                       "Co-Requisite": []},

            "CSE 220":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring","Summer"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Foundational material for further studies in computer science. Topics include logic, proofs, sets, functions, relations, recursion, recurrence relations, mathematical induction, graphs, trees, basic counting theory, regular languages, and context free grammars. This course is the same as MTH 191 and course repeat rules will apply. Students should consult with their major department regarding any restrictions on their degree requirements.",
                       "Pre-Requisite": ["CSE 116"],
                       "Co-Requisite": []},
            "CSE 250":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring","Summer"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Provides a rigorous analysis of the design, implementation, and properties of advanced data structures. Topics include time-space analysis and tradeoffs in arrays, vectors, lists, stacks, queues, and heaps; tree and graph algorithms and traversals, hashing, sorting, and data structures on secondary storage. Surveys library implementations of basic data structures in a high-level language. Advanced data structure implementations are studied in detail. Illustrates the importance of choosing appropriate data structures when solving a problem by programming projects in a high-level language.",
                       "Pre-Requisite": [" CSE 116" "CSE 191", "MTH 311", "MTH 121", "MTH 131", "MTH 141", "MTH 137"],
                       "Co-Requisite": []},
            "CSE 341":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring","Summer"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 2,
                       "Summary":"Basic hardware and software issues of computer organization. Topics include computer abstractions and technology, performance evaluation, instruction set architecture, arithmetic logic unit design, advanced computer arithmetic, datapath and control unit design, pipelining, memory hierarchy, input-output.",
                       "Pre-Requisite": ["EE 178",  "CSE 220", "CSE 241"],
                       "Co-Requisite": []},
            "CSE 331":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring","Summer"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 2,
                       "Summary":"Basic hardware and software issues of computer organization. Topics include computer abstractions and technology, performance evaluation, instruction set architecture, arithmetic logic unit design, advanced computer arithmetic, datapath and control unit design, pipelining, memory hierarchy, input-output.",
                       "Pre-Requisite": ["EE 178",  "CSE 220", "CSE 241"],
                       "Co-Requisite": []},

            "CSE 305":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring","Summer"],
                       "WhenTakeYear" : 3,
                       "WhenTakeSemester": 1,
                       "Summary":"Examines concepts and constructs found in programming languages. Topics include binding time, strong typing, control and data abstraction, higher-order functions, and polymorphism. The major programming paradigms (procedural, object-oriented, functional, and logic) will be studied and compared. The course will also provide an introduction to syntax and semantics, compilation vs. interpretation, and storage management.",
                       "Pre-Requisite": ["CSE 250"],
                       "Co-Requisite": []},

            "CSE 442":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring","Fall"],
                       "WhenTakeYear" : 3,
                       "WhenTakeSemester": 1,
                       "Summary":"Examines concepts and constructs found in programming languages. Topics include binding time, strong typing, control and data abstraction, higher-order functions, and polymorphism. The major programming paradigms (procedural, object-oriented, functional, and logic) will be studied and compared. The course will also provide an introduction to syntax and semantics, compilation vs. interpretation, and storage management.",
                       "Pre-Requisite": ["CSE 250"],
                       "Co-Requisite": []},
            "CSE 442":{"Proffesor":{},
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring","Fall", "Summer", "Winter"],
                       "WhenTakeYear" : 3,
                       "WhenTakeSemester": 1,
                       "Summary":"Considers problems encountered in the design and implementation of a translator for high-level programming languages: lexical analysis, context-free grammars, parsing, storage allocation, code generation and optimization, and error recovery. Uses compiler construction tools for the programming projects. Offered occasionally.",
                       "Pre-Requisite": ["CSE 220"],
                       "Co-Requisite": ["CSE 341"]},
            
            "CSE 494":{"Proffesor":{},
                       "Credits": 3,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring","Fall", "Summer", "Winter"],
                       "WhenTakeYear" : 3,
                       "WhenTakeSemester": 1,
                       "Summary":"Course for senior-level majors intended to provide a learning experience that integrates knowledge from lower-level courses. Topics may vary. (May not be used to satisfy the requirements for the BA or BS unless specifically used as capstone or senior seminar.)",
                       "Pre-Requisite": ["CSE 220"],
                       "Co-Requisite": ["CSE 341"]},

            },

    "EAS": {"EAS 360":{"Proffesor":{},                                           
                       "Credits": 3,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring", "Summer", "Winter"],
                       "WhenTakeYear" : 3,
                       "WhenTakeSemester": 1,
                       "Summary":"Prepares students to successfully communicate, across a range of professional genres and media, to technical, professional, and public audiences; to produce communications individually and as part of a team; and to produce communications which are consistent with ethical engineering practice.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []}
            } ,
        "UBC":{"UBC 399":{"Proffesor":{},                                           
                       "Credits": 31,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring"],
                       "WhenTakeYear" : 3,
                       "WhenTakeSemester": 1,
                       "Summary":"UB Curriculum Capstone (UBC 399) is the culminating general education requirement. It is a one-credit course in which you will work in UBPortfolio, with the support of your Capstone instructor, to create a reflective and integrative Capstone ePortfolio based on your UB Curriculum coursework and lived experiences outside of the classroom. All UB Curriculum courses must be completed or in-progress to enroll in and complete UBC 399. Students who drop an in-progress course will be removed from UBC 399 through the add/drop period. Students who resign an in-progress course may not be able to successfully complete the Capstone.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []}

        }

    

    }

science_dict = {"BIO": {"BIO 200":{"Proffesor":{},                                           
                       "Credits": 5,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring", "Summer", "Winter"],
                       "WhenTakeYear" : 3,
                       "WhenTakeSemester": 1,
                       "Summary":"This course is designed as a general introduction to organismal biology: what happens at the level of the organism and above. Students will learn how evolution works, what organisms evolution has created, and how those organisms interact with the environment and each other. These three topics comprise the three sections of the course material: evolution, diversity, and ecology. Students will gain a general facility with the major topics of each of these fields to prepare them for future courses in the biology department and related fields. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []}

    },
                "CHE": {"CHE 101":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring", "Summer"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Introduces fundamental concepts of chemistry, and surveys important chemical elements and their compounds. The first semester course of a two-semester sequence of general chemistry designed for students in sciences and engineering. Topics include stoichiometry, reactions in solution, thermochemistry, atomic and molecular structure and bonding, gas laws, intermolecular forces, and phases of matter. Three hours of lecture plus one 50-minute recitation weekly. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []},

                        "CHE 102":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring", "Summer"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Introduces fundamental concepts of chemistry, and surveys important chemical elements and their compounds. The second semester course of a two-semester sequence of general chemistry designed for students in sciences and engineering. Topics include properties of solutions, kinetics, equilibria, thermodynamics, electrochemistry, transition metals and coordination chemistry, and nuclear chemistry. Three hours of lecture plus one 50-minute recitation weekly. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": ["CHE 101", "CHE 105", "CHE 107"],
                       "Co-Requisite": []},

                        "CHE 105":{"Proffesor":{},                                           
                       "Credits": 5,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"There is a fee associated with this course. Introduces the principles of chemistry and their applications. For students who are interested in majoring in a chemistry-related science. Three hours of lecture plus one four-hour recitation/laboratory period weekly.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []},

                        "CHE 106":{"Proffesor":{},                                           
                       "Credits": 5,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Introduces the principles of chemistry and their applications. For students who are interested in majoring in a chemistry-related science. Three hours of lecture plus one four-hour recitation/laboratory period weekly. There is a fee associated with this class.",
                       "Pre-Requisite": ["CHE 105"],
                       "Co-Requisite": []},
            
                        "CHE 107":{"Proffesor":{},                                           
                       "Credits": 3.5,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Meets the general chemistry requirement for students wishing to receive an engineering degree. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []},
            
                        "CHE 108":{"Proffesor":{},                                           
                       "Credits": 3.5,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Meets the general chemistry requirement for students wishing to receive an engineering degree. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": ["CHE 101", "CHE 107"],
                       "Co-Requisite": []},
            
                        "CHE 113":{"Proffesor":{},                                           
                       "Credits": 3.5,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"There is a fee associated with this class. Consists of the lab components of CHE 101. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": ["CHE 101", "CHE 107"],
                       "Co-Requisite": []},

                        "CHE 114":{"Proffesor":{},                                           
                       "Credits": 1,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall", "Summer"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Laboratory to accompany CHE 107, General Chemistry for Engineers 1. Experiments focus upon stoichiometry, reactions in aqueous solutions, thermochemistry, and properties of gases. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": ["CHE 101", "CHE 107"],
                       "Co-Requisite": ["CHE 102"]},

                        "CHE 127":{"Proffesor":{},                                           
                       "Credits": 0.5,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Laboratory to accompany CHE 107, General Chemistry for Engineers 1. Experiments focus upon stoichiometry, reactions in aqueous solutions, thermochemistry, and properties of gases. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": [],
                       "Co-Requisite": ["CHE 107"]},

                        "CHE 128":{"Proffesor":{},                                           
                       "Credits": 0.5,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Laboratory to accompany CHE 108, General Chemistry for Engineers 2. Experiments focus upon kinetics, chemical equilibria, acid-base chemistry, electrochemistry and coordination chemistry. This course is a controlled enrollment (impacted) course. Students who have previously attempted the course and received a grade other than W may repeat the course in the summer or winter; or only in the fall or spring semester with a petition to the College of Arts and Sciences Deans’ Office.",
                       "Pre-Requisite": [],
                       "Co-Requisite": ["CHE 107"]},

    },
                "GLY": {"GLY 101":{"Proffesor":{},                                           
                       "Credits": 3,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"This Scientific Literacy and Inquiry course explores the solid Earth and ways that ongoing, natural processes act to harm people and property. The course aims to put geological hazards in a broader context by examining the latest science at the micro (e.g., minerals), human (e.g., why tsunamis are such efficient and massive killers) and global (e.g., global effects of asteroid impacts or super volcano eruptions) scales. We will examine the history of scientific discovery and thought about natural hazards and global catastrophes on both human and geologic timescales. We will use case studies and debates to clarify science vs. pseudo-science, current controversies, and how natural (as well as some human-induced) hazards affect us in Western New York. Completing all three courses, GLY 101LEC, GLY 102 and GLY 105, would fulfill the Scientific Inquiry and Literacy Requirement as well as the Natural Sciences General Education requirement.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []},

                       "GLY 102":{"Proffesor":{},                                           
                       "Credits": 3,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"This Scientific Literacy and Inquiry course offers an interdisciplinary discussion of both natural and human-induced global environmental and climate change at various scales (space and time). Provides a comprehensive description of how advances in the physical, biological, and geological sciences are being integrated to understand the interplay between the Earths components (atmosphere, hydrosphere, lithosphere, and biosphere). Topics include glaciers, basic oceanography and atmospheric science, natural hazards, natural resources, and Earth system cycles (such as weather, climate change, and atmospheric pollution). Completing all three courses, GLY 101, GLY 102LEC and GLY 105, would fulfill the Scientific Inquiry and Literacy Requirement as well as the Natural Sciences General Education requirement.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []},

                        "GLY 103":{"Proffesor":{},                                           
                       "Credits": 3,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"This course introduces engineers and others to the Earth system, by examining the latest science at the micro (e.g., minerals), human (e.g., why earthquakes are such efficient and massive killers) and global (e.g., water cycle) scales. We examine the use of scientific hypothesis testing and implications for understanding Earth materials and natural hazards. We use case studies to clarify science vs. pseudo-science, current controversies, and how natural (as well as some human-induced) hazards affect us.",
                       "Pre-Requisite": [],
                       "Co-Requisite": []},

                       "GLY 104":{"Proffesor":{},                                           
                       "Credits": 1,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"Historical Geology provides the student with a comprehensive survey of the history of life and major events in the physical development of Earth. Most importantly, this class addresses how processes like plate tectonics and climate interact with life, forming an integrated system. The first half of the class focuses on theoretical concepts within both the biosphere and lithosphere (e.g., tectonics, earth sciences, evolution) and the second portion of the course will focus on a chronologic overview of major biological and physical events in different geologic periods. This lab course aims to enhance student Earth science college-level content knowledge, awareness, and analysis and critical thinking skills in a broad context by examining the temporal, regional and global (e.g., climate and ecological change through time) scales. This course is designed to develop skills in map-reading, cladistics/systematics, problem-solving, and to foster learning of the interactions between Earth processes, the environment, and the biosphere. We will apply the scientific method and foster student analysis of scientific data and models to evaluate leading concepts in both geological and paleontological science.",
                       "Pre-Requisite": [],
                       "Co-Requisite": ["GLY 101", "GLY 102", "GLY 137"]},

                       "GLY 105":{"Proffesor":{},                                           
                       "Credits": 1,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"This Scientific Literacy and Inquiry lab course aims to put Earth science in a broader context by examining the latest science at the micro, human (e.g., climate change impacts and mitigation) and global (e.g., global warming) scales. It is designed to develop skills in map-reading, problem-solving, and to foster hands-on learning of the interactions between Earth processes, the environment, and humans. We will apply the scientific method and foster student analysis of scientific data and models to evaluate leading concepts in Earth science. Finally, through case studies and debates, it will discuss science vs. pseudo-science, current controversies, and how earth science affects our everyday lives.",
                       "Pre-Requisite": [],
                       "Co-Requisite": ["GLY 101", "GLY 102", "GLY 137", "GLY 103"]},
                },
                "PHY":{"PLY 107":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall", "Summer", "Winter"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"A calculus-based introductory course primarily for chemistry, engineering, and physics majors. Covers kinematics, Newton’s laws, energy, momentum, rotational motion, and oscillations. This course satisfies 4 credits as required by different majors and also 4 credits (out of the mandated 7 credits total) of UB’s Science Literacy and Inquiry general education requirement sequence. Enrollment is not allowed in PHY107 if a student has current enrollment in PHY 101.",
                       "Pre-Requisite": ["MTH 141",  "MTH 136",  "MTH 137"],
                       "Co-Requisite": ["MTH 141",  "MTH 136",  "MTH 137"]},

                       "PLY 108":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring", "Fall", "Summer", "Winter"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"A calculus based introductory course primarily for chemistry, engineering, and physics majors. Covers the electric field, Gauss’ law, electric potential, capacitance, DC circuits, RC circuits, magnetic field, Faraday’s law, inductance, LR circuits, AC circuits, and Maxwell’s equations. This course satisfies 4 credits as required by different majors and also 4 credits (out of the mandated 7 credits total) of UB’s Science Literacy and Inquiry general education requirement sequence.",
                       "Pre-Requisite": ["PHY 107" , "PHY 117"],
                       "Co-Requisite": ["MTH 141",  "MTH 136",  "MTH 137"]},

                       "PLY 117":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": [ "Fall"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"PHY 117 is a calculus based Honors physics course, which covers similar topics as PHY 107, but in greater depth. This course is intended for potential physics majors, students in the honors college, and advanced students in other majors (with permission from the instructor). The class will be taught at a level comfortable for students who would receive a B or higher in a typical PHY 107 class. Because of the higher average GPA of students in this class, grading will be adjusted to reflect this quality, rather than following the conventional curves used for PHY 107. Introductory materials, such as review of trigonometry, vectors and calculus, in PHY 107 will not be covered. This leaves room to expose students to a wider range of interesting applications of Newtonian mechanics, and recent developments in topics such as Special Relativity and Cosmology. The class size is limited, to encourage interactive learning and communications between students and the instructor. This course satisfies 4 credits (out of the mandated 7 credits total) of UB’s Science Literacy and Inquiry General Education requirements. Enrollment is not allowed in PHY117 if a student has current enrollment in PHY 107.",
                       "Pre-Requisite": ["PHY 107" , "PHY 117"],
                       "Co-Requisite": ["MTH 141",  "MTH 136",  "MTH 137"]},

                       "PLY 118":{"Proffesor":{},                                           
                       "Credits": 4,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Spring"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"PHY 118 is a calculus based Honors physics course, which covers the same topics in electricity and magnetism as PHY 108, but in greater depth. Class size is limited. In general taken by students in the University Honors College, but other students may take it with permission of instructor. This course satisfies 4 credits as required by different majors and also 4 credits (out of the mandated 7 credits total) of UB’s Science Literacy and Inquiry sequence general education requirements. Enrollment is not allowed in PHY118 if a student has current enrollment in PHY 108.",
                       "Pre-Requisite": ["PHY 107" , "PHY 117"],
                       "Co-Requisite": []},

                       "PLY 158":{"Proffesor":{},                                           
                       "Credits": 1,
                       "Grading": "Graded (GRD)",
                       "Typically Offered": ["Fall", "Spring", "Summer"],
                       "WhenTakeYear" : 2,
                       "WhenTakeSemester": 1,
                       "Summary":"PHY-158 is an introductory Physics lab course. This course covers mechanics, kinematics, forces, vectors, electricity and magnetism. Experiments are used to demonstrate principles discussed in the lecture courses PHY 107 and PHY 108. PHY-158 satisfies the SLI General Education 1-credit laboratory requirement (out of the 7 credits total SLI Gen-Ed requirement).",
                       "Pre-Requisite": ["PHY 107" , "PHY 117"],
                       "Co-Requisite": [ "PHY 108", "PHY 118"]},

                }
            
            
}       
    

pathway_dict = {}








